main: iomatix.spigot.RPGMobsparties.Main
softdepend: [SkillAPI, RPGLeveledMobs,MCCore]
load: POSTWORLD
name: RPGMobsParties
version: 1.0
api-version: 1.14
author: iomatix
description: Parties plugin supports RPGLeveledMobs with SkillAPI.
commands:
  rpgmobs:
    description: RPGMobsParties prefix.
    usage: /pt
    permission: party.general
    permission-message: You do not have party.general permission to use this command.