# Maximum size of a party
max-size: 6
#
# How long an invitation lasts in seconds
# before it is automatically cancelled
invite-timeout: 30
#
# Whether or not to remove players
# when they disconnect
remove-on-dc: true
#
# Whether or not to assign a new party leader
# when the current one disconnects
new-leader-on-dc: true
#
# Whether or not to use the scoreboard for
# displaying party information
use-scoreboard: false
#
# Whether or not to show levels in the scoreboard
# A value of "false" will show health instead
level-scoreboard: true
#
# Whether or not only the leader of a party
# can invite new members
only-leader-invites: true
#
# Whether or not to show debug messages
debug-messages: false
#
# The type of sharing to use for items retrieved by a party
# The options are:
#   none             | whoever picks up an item keeps it
#   sequential       | evenly distributes items received, breaking up stacks
#   random           | randomly distributes items, breaking up stacks
#   sequential-stack | evenly distributes items received, not breaking up stacks
#   random-stack     | randomly distributes items, not breaking up stacks
item-sharing: none
#
# Modifications to experience gained (SkillAPI feature, RPGMobs supported)
exp-modifications:
  #
  # Modifier for the number of members
  # normally ranging from 0 to 1.
  # 0 -> Full experience for all members.
  # 1 -> Split experience.
  # 0-1 range increases the total experience gain. 1 and more decreases the total experience gain. (For parties)
  # So values above 1 will result as a Party Penalty.
  members: 0.75
  #
  # Modifier for the difference in level
  # between party members.
  # Generally should be small decimals.
  # (0 - 0.01 is a good range)
  # 0 -> No change in experience.
  level: 0.003
  #
  # Modifications to money gained (RPGMobs feature)
money-modifications:
  #
  # Modifier for the number of members
  # normally ranging from 0 to 1
  # 0 -> Full money for all members
  # 1 -> Split money
  # 0-1 range increases the total income. 1 and more decreases the total income. (For parties)
  # So values above 1 will result as a Party Fee.
  members: 1
  #
  # Modifier for the difference in level
  # between party members.
  # Generally should be small decimals.
  # (0 - 0.01 is a good range)
  # 0 -> No change in income.
  level: 0
#
# Max distance in blocks for EXP sharing feature. 
# -1 -> share it everywhere, even in different worlds. 
# Recommended range is 32-80. (2 - 5 chunks).
distance-sharing: 48