main: iomatix.spigot.RPGParty.Parties
depend: [SkillAPI]
softdepend: [Instances,MCCore,RPGLeveledMobs,Vault]
name: RPGParties
version: 1.6.1
api-version: 1.14
author: iomatix
description: Parties plugin designed for SkillAPI which supports RPGLeveledMobs plugin.
permissions:
  party.general:
    description: RPGParties prefix.
    default: true