main: iomatix.spigot.RPGParty.Parties
depend: [SkillAPI]
softdepend: [Instances,MCCore,RPGLeveledMobs,Vault]
name: RPGParties
version: 1.0
api-version: 1.14
author: iomatix
description: Parties plugin supports RPGLeveledMobs with SkillAPI.
permissions:
  party.general:
    description: RPGParties prefix.
    default: true